packages:
  - packages/*
  - integration-test

catalog:
  '@ant-design/icons': ^6.0.0
  '@eslint/js': ^9.39.3
  '@testing-library/jest-dom': ^6.9.1
  '@testing-library/react': ^16.3.2
  '@types/node': ^24.10.11
  '@types/react': ^19.2.13
  '@types/react-dom': ^19.2.3
  '@vitejs/plugin-react': ^5.1.3
  '@vitest/browser': ^4.0.18
  '@vitest/browser-playwright': ^4.0.0
  '@vitest/coverage-v8': ^4.0.0
  '@vitest/ui': ^4.0.0
  antd: ^6.3.1
  babel-plugin-react-compiler: ^1.0.0
  commander: ^14.0.3
  dayjs: ^1.11.19
  eslint: ^9.39.2
  eslint-plugin-react-compiler: ^19.1.0-rc.2
  eslint-plugin-react-hooks: ^7.0.1
  globals: ^17.3.0
  immer: ^11.1.3
  jsdom: ^28.0.0
  msw: ^2.12.9
  nanoid: ^5.1.6
  playwright: ^1.58.2
  prettier: ^3.8.1
  react: ^19.2.4
  react-compiler-runtime: ^1.0.0
  react-dom: ^19.2.4
  react-use: ^17.6.0
  reflect-metadata: ^0.2.2
  ts-morph: ^27.0.2
  typescript: ^5.9.3
  typescript-eslint: ^8.56.1
  unplugin-dts: 1.0.0-beta.6
  vite: ^7.3.1
  vite-bundle-analyzer: ^1.3.6
  vitest: ^4.0.18
  yaml: ^2.8.2
